### ISSUE TITLE
Stacking filterBy and filterByImpure documentation suggestion

### ISSUE THREAD

**Issue by msholly** [danrevah/ngx-pipes#101]
I wanted to suggest some additional documentation that I hope someone could also benefit from. 

I was looking for a way to have multiple filters based on a dropdown selection as well as a user input field for standard searches. If, for example, a user wanted to show only Sales Department users and then search within those results. On a hunch, I just added a second filterByImpure:

`      <ion-item-sliding *ngFor="let user of users | orderBy:orderBySetting | filterByImpure: ['department']: selectedDept.id | filterByImpure: ['fname','lname']: searchTerm" (tap)="goToDetails(user)" #slidingItem>
`

Probably obvious to many users, but the documentation doesn't suggest this should work. And it works beautifully. This approach might even work for other pipes, but I have not tested. 

Thank you very much for your work on this library.

**Comment by danrevah** [comment]
every pipe can be 'stacked' it's an Angular feature, but it might be worth mentioning it in the comments for those who aren't sure. Is that what you meant?

Thank you for you feedback 👍

**Comment by msholly** [comment]
Good to know! Yes exactly. I knew you could combine different pipes on the same value, but didn't know you could duplicate the same pipe. Thanks again
