### ISSUE TITLE
extractDeepProperty in own Pipe

### ISSUE THREAD

**Issue by Meistercoach83** [danrevah/ngx-pipes#104]
Good Morning!

is it possible to use the extractDeepPropertyByMapKey in my own pipes? When I try to import it like 
import { extractDeepPropertyByMapKey } from 'ngx-pipes/src/pipes/helpers/helpers';

I get an error, that  it can´t be resolved.

**Comment by danrevah** [comment]
I wouldn't suggest on using those helper functions, they are suppose to be `private` to be used as part of library functions.

I'm not documenting them since they might change, and their behaviour might change as well.

If you need such a function I'd suggest to copy the code into your own project.
