### ISSUE TITLE
Question: How to use group by pipe for partial title?

### ISSUE THREAD

**Issue by CodeLearner21** [danrevah/ngx-pipes#107]
First of all thanks for the great module.

I am able to use groupBy pipe for title field. I want to group data by partial title, not full title compare.
I tried this by creating a custom function which is not working.
`renderTitle(value: string) {
    let articleName = value.split('-');
    return articleName[0]
  }`
and in template
`*ngFor="let post of posts | groupBy: renderTitle('title') | pairs`

here are some title value variations.

Lorem ipsum dolor - sit amet
Lorem ipsum dolor - consectetur adipiscing
Lorem ipsum dolor - labore et - dolore magna

and I want to group this by 'Lorem ipsum dolor'

Thanks in advance.

**Comment by danrevah** [comment]
Not quite sure about your datastructure, so I've assumed it's an array of objects with a property `title`.

This seems to be working for me:

```typescript
const arrayWithDiscriminator = [
      {title: 'Lorem ipsum dolor - sit amet'},
      {title: 'Lorem ipsum dolor - consectetur adipiscing'},
      {title: 'Lorem ipsum dolor - labore et - dolore magna'}
    ];

    const result = pipe.transform(arrayWithDiscriminator, (_: any) => _['title'].split('-')[0].trim());

    expect(result).toEqual({
      'Lorem ipsum dolor': [
        {title: 'Lorem ipsum dolor - sit amet'},
        {title: 'Lorem ipsum dolor - consectetur adipiscing'},
        {title: 'Lorem ipsum dolor - labore et - dolore magna'}
      ]
    });
```

**Comment by CodeLearner21** [comment]
Thanks for quick reply danrevah, but I am new to Angular development and quite confused where should I write this code. Do I need to write this in the component or it will be a new custom pipe, and also how do I call this with *ngFor statement. 

I would be thankful if you could help me with details.

**Comment by danrevah** [comment]
This kind of questions are more related to StackOverflow.com than here. 

Anyway the code I wrote was a unit-test and not something you needed to write some where..

I could try and help you if you will show your exact data strucure the value of the variable 'posts'
