### ISSUE TITLE
[Suggestion] Average pipe on math module

### ISSUE THREAD

**Issue by iget-master** [danrevah/ngx-pipes#114]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

* **Ngx-pipes version:** Any version

**Current behavior**
-

**Expected behavior**

The `average` pipe should be added to the Math pipes module, and return the average value for the given array of numbers.

**Comment by danrevah** [comment]
Good idea, is any one up for contributing it? 
Don't forget to add tests and everything :)

**Comment by danrevah** [comment]
@kreatemore I've seen your PR about a week ago, and had some requested changes. 
do you want to fix them and send again?

**Comment by danrevah** [comment]
Released in `v2.4.4`.

**Comment by danrevah** [comment]
https://github.com/danrevah/ngx-pipes#average

**Comment by iget-master** [comment]
Thanks @danrevah. Didn't seen your message asking for changes. Thanks for finishing it and merging.
