### ISSUE TITLE
Reverse pipe for FormArray controls

### ISSUE THREAD

**Issue by reyryan** [danrevah/ngx-pipes#115]
Hey guys,

Thank you for this wonderful library. However, I am wondering if the 'reverse' pipe can be used to reverse the display of formArray control from ReactiveFormsModule. If so, how can I do that?

TIA.

**Comment by danrevah** [comment]
reverse pipe is just a simple call, using the `Array.prototype.reverse`. 
It all depends on the data you are trying to 'reverse', I'm not quite sure about the ReactiveFormsModule.
