### ISSUE TITLE
is empty Object

### ISSUE THREAD

**Issue by zymr-keshav** [danrevah/ngx-pipes#116]
**I'm submitting a ...**
```
[ X ] feature request
```

* **Ngx-pipes version:** 2.1.0

**Current behavior**
There is no pipe to check whether the given object is empty

**Expected behavior**

there should be one method to check whether a given object is Empty Object

I have written this method which can be turned into the pipe
```
import { PipeTransform, Pipe } from '@angular/core';

@Pipe({ name: 'isEmpty' })
export class isEmptyPipe implements PipeTransform {
    transform(value): boolean {
     return (value && (Object.keys(value).length === 0));
}

```

**Please tell us about your environment:**

macOS 10.13.5
vscode 1.25.0

* **Angular version:** 4.4.3

**Comment by danrevah** [comment]
It's not exactly clear about what does it mean an 'empty object', I'm not quite sure this is something which is commonly used and should be added to ngx-pipes.

Let's wait and see if there's any more people thinks it should be in the lib.

**Comment by zymr-keshav** [comment]
many times we need to check whether a given variable ( which is the object type) have some value or empty object ?

**Comment by danrevah** [comment]
Well, it is possible.

```html
<div>{{ (obj | keys).length }}</div>
```

It might not be the nicest syntax, but this is possible.

I'm closing this, since I don't think it requires a special pipe.
