### ISSUE TITLE
 Metadata version mismatch for module ...  found version 4, expected 3

### ISSUE THREAD

**Issue by sandroweb** [danrevah/ngx-pipes#120]
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

* **Ngx-pipes version:** 2.3.5

**Current behavior**

> ERROR in Error: Metadata version mismatch for module /node_modules/ngx-pipes/ngx-pipes.d.ts, found version 4, expected 3, resolving symbol AppModule in /src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.ts

**Minimal reproduction of the problem with instructions**
I'm using the BytesPipe imported in `*.ts` file.

When I run `$ ng serve`, it show me this error, but if I not to cancel this command and ignore that error, when I to save anyfile after, this process will watch my action and will build with success.

**Please tell us about your environment:**
Windows 10
Angular CLI: 1.6.8
Node: 8.11.3
OS: win32 x64
Angular: 4.4.6
@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.6.8
@angular/flex-layout: 2.0.0-rc.1
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.3.4
webpack: 3.11.0

**Comment by danrevah** [comment]
Seems like this is some what related to angular 4.
https://github.com/angular/material2/issues/8229#issuecomment-342502556

Try to update to Angular 5+, and please let me know if this helps.
