### ISSUE TITLE
filterBy function not return exact array when the values contents similar words with comma

### ISSUE THREAD

**Issue by datasinfo** [danrevah/ngx-pipes#121]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

* **Ngx-pipes version:** 2.3.5

**Current behavior**

The filterBy function not return exact array when the values contents similar words with comma.
For example:
```
const students = [
{
    "Name": "S1"
    "Status": "Active, S1"
},
{
    "Name": "S2"
    "Status": "Active, S2"
},
{
    "Name": "S3"
    "Status": "Active, S3"
}
]
```

In my HTML:
`{{ (students | filterBy: ['Status']: 'Active, S2').length }}`
The code above gives me the length of object `3` which return all the `Status `equal to `Active`

**Expected behavior**

It should return only the `S2` object which has length `1`

**Please tell us about your environment:**

* **Angular version:** 6.0.X

Is there any solution for me here? 

Thanks!

**Comment by datasinfo** [comment]
Problem solved by add `strict `option
`{{ (students | filterBy: ['Status']: 'Active, S2': [true]).length }}`

**Comment by cse-t-kutsuna** [comment]
In the current version, search is split with commas regardless of strict mode, so it seems to return an empty array.

https://github.com/danrevah/ngx-pipes/blob/0dc750969273e25029d0c55ea77edfcfeca4cad0/src/pipes/array/filter-by.ts#L26
