### ISSUE TITLE
Upgrading to v7 of Angular

### ISSUE THREAD

**Issue by DuncanFaulkner** [danrevah/ngx-pipes#128]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```
* **Ngx-pipes version:** 2.3.5

**Current behaviour**
After upgrading to v7 Angular the following message is reported 
 ngx-pipes@2.3.5 requires a peer of @angular/core@^4.0.1 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself. 

**Expected behaviour**
Update of dependencies to include version 7.0.0

**Please tell us about your environment:**
Ubuntu 18.04.1

* **Angular version:** 7.0.0
Latest version

**Comment by danrevah** [comment]
Released in `ngx-pipes@2.3.6`
