### ISSUE TITLE
Enhance pluck to work on Object instead of only Array

### ISSUE THREAD

**Issue by aaronfrost** [danrevah/ngx-pipes#129]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
```

* **Ngx-pipes version:** 1.X.X

**Current behavior**

`pluck` pipe returns the obj if it isn't an array. If it is an array, it uses `extractDeepPropertyByMapKey` to extract the deep property from each obj in the array. 

**Expected behavior**

Instead of returning the non-array object, you should return the `extractDeepPropertyByMapKey` of the object. That way, the pluck pipe can be used on an array of object as well as on an object itself. 

**Minimal reproduction of the problem with instructions**

add ` {{ obj | pluck: 'address.city'  }}` to a template. Instead of plucking the value out of the obj, it just returns the object. When you give it an array, it pluck each object in the array. So it seems like if giving just an obj, it would return the plucked object.

**Comment by danrevah** [comment]
Released in @ v.2.3.10
