### ISSUE TITLE
Wrong name

### ISSUE THREAD

**Issue by oehm-smith** [danrevah/ngx-pipes#13]
The instructions at https://www.npmjs.com/package/ng2-pipes#tail and https://github.com/danrevah/ngx-pipes say:

```
import {NgPipesModule} from 'ngx-pipes';
```

Though it should be:

```
import {NgPipesModule} from 'ng2-pipes';
```

**Comment by pkleckner** [comment]
#9 

Looks like as of about 7 days ago, this issue was fixed. `ngx-pipes` works for me.

**Comment by danrevah** [comment]
The library was first named `ng2-pipes` and after #9 it was renamed to `ngx-pipes`.
I'm still publishing to both names on npm.

**Comment by oehm-smith** [comment]
Ok.  Though Intellisense didn't know about the ngx name.
