### ISSUE TITLE
New pipe to a/an-prefix words

### ISSUE THREAD

**Issue by cpilson** [danrevah/ngx-pipes#132]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
```

* **Ngx-pipes version:** `2.3.6`

**Current behavior**
Must write one-offs to a/an-prefix entities in templates.

**Expected behavior**
With this pipe, you could pass in an entity within a template, not care what the entity is actually named, and the pipe would prefix a/an appropriately.

**Minimal reproduction of the problem with instructions**
Not a bug, but if you work in templates and want to have cleaner code there, this could help.

**Please tell us about your environment:**
macOS, npm, Angular, Node.

* **Angular version:** `6.0.9`
```
Angular CLI: 6.0.8
Node: 8.10.0
OS: darwin x64
Angular: 6.0.9
```

* **Node (for AoT issues):** `node --version` =   `v8.10.0`

**Comment by danrevah** [comment]
Released in @ v2.3.8
