### ISSUE TITLE
filterBy with list of keys

### ISSUE THREAD

**Issue by aebrahimian** [danrevah/ngx-pipes#136]
I have an array like this.
```
[{
'type': 'a'
},
{
'type': 'b'
},
{
'type': 'c'
}]
```

and i want to filter it with filterBy pipe. but i want to pass list of keys instead of one key to use it with multiple select input like this:

`<tr *ngFor="let item of items | filterByImpure: ['type']: types">`

which types is ['a', 'b']

**Comment by danrevah** [comment]
Added to @ v2.3.7
