### ISSUE TITLE
Maybe lpad/rpad should support Number type data source

### ISSUE THREAD

**Issue by haoliangwu** [danrevah/ngx-pipes#139]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

hi, really awesome library and thanks for you hard work. 

But I met some problems when I used `lpad` pipe. That was when I used it with `ngForOf` directive together, I found it didn't work as expected to transform `ngForOf` index variable, then I finally found it was designed deliberately only transform `String` type data according to the repo souce code.

Although I can solve it by the workaround something like: 
```
{{ index + '' | lpad:2:'0'}}
```
but I think it looked like a little verbose. 

So, what's your opinion about `lpad` pipe not only support String type data but also Number type?

**Comment by haoliangwu** [comment]
related issue #10

**Comment by danrevah** [comment]
It's possible to use convert the number to string as shown in the docs:

```html 
<p>{{String(3) | lpad: 5: '0'}}</p> <!-- Output: "00003" -->
```

I kept this issue to see if anyone else thinks different, but I'm closing this now since I really think it's best to explicitly convert to String.
