### ISSUE TITLE
Make the pipes as @Injectable. So that we need not add it as a provider

### ISSUE THREAD

**Issue by Mohendran** [danrevah/ngx-pipes#142]
**I'm submitting a ...**  (check one with "x")
```
[x ] feature request
```

**Current behavior**
We need to add providers and only then we can use it in *.ts.

**Expected behavior**
Add @Injectable to all the pipes with 'providedIn' as 'root'. So that there is no need to add it as a provider.

**Comment by danrevah** [comment]
The @injectable decorator should be used for services and not for pipes.

https://angular.io/api/core/Injectable

**Comment by Mohendran** [comment]
@danrevah Yes, I understand that, But what if I need to use it in the component.ts...

**Comment by danrevah** [comment]
you can inject it as a provider like in the README file :)

**Comment by Mohendran** [comment]
@danrevah I mean to make it as a tree-shakable service... Adding it to a provider would make it non-treeshakable...

**Comment by Mohendran** [comment]
By adding @Injectable with providedIn, we are eliminating the need to add a line to include providers in the component
