### ISSUE TITLE
angular4 reactive, formgroups or formcontrol

### ISSUE THREAD

**Issue by jcdsr** [danrevah/ngx-pipes#143]
I install your package with angular 4.4.6 using HttpClient, reactive forms.

I try to order the form results by using your orderBy pipe, but seems not working, any ideas why?

This is what I use

` <div *ngFor="let dat of rForm.get('collection').controls | orderBy: '-amount'; index as i" [formGroupName]="i" class="ui-g-12"></div>`

"collection" is a simple json as:

```
{
  "collection": [
    {
      "section": "Collect",
      "id": "1"
    },
    {
      "section": "Collec 3",
      "id": "3"
    }
    {
      "section": "Collect 2",
      "id": "2"
    }
]
}
```

**Comment by danrevah** [comment]
your question might be missing something. but from what I see you are trying to order by 'amount' and it's not part of your array of objects?

If this is not the issue please reopen this issue and use `JSON.stringify(rForm.get('collection').controls)` with the output here.
