### ISSUE TITLE
Pluck not creating an array

### ISSUE THREAD

**Issue by pkleckner** [danrevah/ngx-pipes#15]
Okay, I'm stumped. The question may end up being a broader problem and fall outside of `ngx-pipes`, but this package has been great so far.

I working with an API (built with Node.js, Express, Mongoose, and Node-Restful) that has a structure similar to this:

```
finances: [ {
        project_number: Number,
        history: {
            fees: [ {
                amount: Number,
                title: String,
                description: String
            } ]
        }
    } ]
```

Currently I have two records in `fees[ ]`. As a simple example:

```
fees: [ {
   amount: 400,
   title: "Foo",
   description: "Lorem Ipsum"
},
{
   amount: 200,
   title: "Bar",
   description: "Text here"
} ]
```

I've managed to utilize `*ngFor` to break down all of the arrays as necessary, and it's all going well:

`<span *ngFor="let fee of finances.history.fees">{{ fee.amount }}</span>`

That nets me the two Numbers (the type I defined in the API) that I have recorded: 400 and 200. It isn't an array of the two values, just an iteration of the values; it prints out as 400200.

I thought I'd use Pluck to grab the `amount` values prior to binding:

`<span *ngFor="let fee of finances.history.fees | pluck: 'amount'">{{ fee }}</span>`

But again, it doesn't come out as an array. (I've double checked this using `isArray`, which responds as "`falsefalse`", and `isNumber`, which responds as "`truetrue`".)

My end goal is to grab all of the values of each `amount` and run them through the `SumPipe`, but I can't figure out a way to collect those values and push them into an array; they come out as `Numbers`. And thus, the `SumPipe` doesn't work on them.

I'll admit that I'm brand new to node.js/express APIs, and I only adopted Angular this past autumn. But if anyone has any recommendations for me, I would greatly appreciate the assistance.

**Comment by danrevah** [comment]
You don't need to iterate over the elements in order to sum them.
Try this one:

```typescript
finances = {
    history: {
      fees: [ {
        amount: 400,
        title: 'Foo',
        description: 'Lorem Ipsum'
      },
        {
          amount: 200,
          title: 'Bar',
          description: 'Text here'
        } ]
    }
  };
```

```html
<p>Sum: {{finances.history.fees | pluck: 'amount' | sum }}</p> // Print: 600
```

**Comment by pkleckner** [comment]
Perfect! I figured I was missing something super simple, so thank you so very much!
