### ISSUE TITLE
NgStringPipesModule is not a reference: [object Object] error when compiling with ivy

### ISSUE THREAD

**Issue by jeroenvheel** [danrevah/ngx-pipes#150]
[X ] bug report

* **Ngx-pipes version:** 2.5.0

**Current behavior**
When turning ivy on we get this error :

> ERROR in Value at position 12 in the NgModule.declarationss of NgStringPipesModule is not a reference: [object Object]

**Expected behavior**
There should be no error

**Minimal reproduction of the problem with instructions**
upgrade a project to Angular 8
turn ivy on in the tsconfig.app.json
```
  "angularCompilerOptions": {
    "enableIvy": true
  },
```

**Please tell us about your environment:**
Windows 10 x64 Pro
Visual Studio Ent. 2019 16.0.1

* **Angular version:** 8.0.0

* **Node (for AoT issues):**  12.3.1

**Comment by danrevah** [comment]
that's a bug indeed.. will look into it soon..

PR are welcome!

**Comment by danrevah** [comment]
@jeroenvheel are you sure this one related to ivy?
I wasn't unable to get this error.

Have you tried setting up a fresh angular project 
`ng new proj` & `npm i ngx-pipes`
with this configuration?

**Comment by jeroenvheel** [comment]
@danrevah Created a new app and added ngx-pipes and stil have the same error
here is a sample app i created https://we.tl/t-RHhAsGuKdX

**Comment by danrevah** [comment]
@jeroenvheel this is not related to `ngx-pipes`. Also next time please upload to a Github repo and not as a zip file.

I managed to make this work with minor configuration changes:

1. Move from `tsconfig.json` to `tsconfig.app.json`:

```typescript
"angularCompilerOptions": {
    "enableIvy": true
  }
```

2. In `tsconfig.json` change 'target' from 'es5' to 'es2015'.
This seems to be safe since `Angular-CLI` automatically generates this file with 'es2015' as the target.

**Comment by elementalPRESS** [comment]
Doesn't work

**Comment by danrevah** [comment]
Does anybody

**Comment by Flasheur111** [comment]
Any update on that one?

**Comment by danrevah** [comment]
Yeah. a fixed was released in 'v2.5.5'.

Please update me if it works for you guys too..

Commit: https://github.com/danrevah/ngx-pipes/commit/d4e619294a65da6f74349d935a4dfe223f0b9361

Issue was related to the latinise pipe, which for some reason caused issues with ngrcc as es5 module. :| Voodo is _**not**_ fun

**Comment by Flasheur111** [comment]
I confirm this is working as expected in the last version published, thanks!

**Comment by danrevah** [comment]
Good news!

Everyone else: if there's any related issue, please open a new ticket.
