### ISSUE TITLE
Allow filterPipe to filter with AND as well as OR

### ISSUE THREAD

**Issue by Slavrix** [danrevah/ngx-pipes#156]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
```
Allow filterPipe to filter with AND as well as OR

**Comment by danrevah** [comment]
it's not going to be supported out-of-the-box, but you could concatenate two filterBy filters in order to achieve this.
