### ISSUE TITLE
I recommend merging with https://github.com/fknop/angular-pipes

### ISSUE THREAD

**Issue by born2net** [danrevah/ngx-pipes#16]
I recommend merging with https://github.com/fknop/angular-pipes
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by fknop** [comment]
Hello,

I answered here: https://github.com/fknop/angular-pipes/issues/36

**Comment by danrevah** [comment]
Thanks for letting me know about it.
I will consider merging it, I will take a look at his repo soon.
