### ISSUE TITLE
type of any..

### ISSUE THREAD

**Issue by bonaparte89** [danrevah/ngx-pipes#17]
would be great to remove those 'warnings'

`/ngx-pipes/src/app/pipes/array/diff.ts(8,29): error TS7006: Parameter 'elm' implicitly has an 'any' type.
    /ngx-pipes/src/app/pipes/array/intersection.ts(12,28): error TS7006: Parameter 'elm' implicitly has an 'any' type.
    /ngx-pipes/src/app/pipes/array/sample.ts(11,9): error TS7005: Variable 'sample' implicitly has an 'any[]' type.
    /ngx-pipes/src/app/pipes/array/union.ts(12,46): error TS7006: Parameter 'noDupArr' implicitly has an 'any' type.
    /ngx-pipes/src/app/pipes/array/union.ts(12,56): error TS7006: Parameter 'curr' implicitly has an 'any' type.
    /ngx-pipes/src/app/pipes/helpers/helpers.ts(30,16): error TS7017: Index signature of object type implicitly has an 'any' type.
    /ngx-pipes/src/app/pipes/object/invert-by.ts(14,28): error TS7017: Index signature of object type implicitly has an 'any'type.
    /ngx-pipes/src/app/pipes/object/invert-by.ts(15,12): error TS7017: Index signature of object type implicitly has an 'any'type.
    /ngx-pipes/src/app/pipes/string/camelize.ts(12,55): error TS7006: Parameter 'v' implicitly has an 'any' type.
    /ngx-pipes/src/app/pipes/string/camelize.ts(12,70): error TS7006: Parameter 'word' implicitly has an 'any' type.
    /ngx-pipes/src/app/pipes/string/camelize.ts(12,76): error TS7006: Parameter 'key' implicitly has an 'any' type.
    /ngx-pipes/src/app/pipes/string/latinise.ts(12,39): error TS7006: Parameter '_' implicitly has an 'any' type.
    /ngx-pipes/src/app/pipes/string/latinise.ts(12,45): error TS7017: Index signature of object type implicitly has an 'any' type.
    /ngx-pipes/src/app/pipes/string/underscore.ts(9,33): error TS7006: Parameter 'c' implicitly has an 'any' type.
    /ngx-pipes/src/app/pipes/string/underscore.ts(9,36): error TS7006: Parameter 'k' implicitly has an 'any' type.`

**Comment by danrevah** [comment]
It's happens because your typescript compiler is set to `noImplictAny: true` make sure to set it to false:  https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
