### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by timrasche** [danrevah/ngx-pipes#170]

**Comment by danrevah** [comment]
There's seems to bug some kind of a problem with Angular 9: https://github.com/angular/angular/issues/35255

I did upgrade to Angular 9 - but seems like there's a known few issues there..

I haven't been working for Angular for quite a while, so I'd have to follow this topic and see if they are able to solve it.

**Comment by danrevah** [comment]
Nevermind.. was able to solve this by upgrading `ng-packagr`.
