### ISSUE TITLE
FilterBy Pipe returning generic `any[]`

### ISSUE THREAD

**Issue by mboudreau** [danrevah/ngx-pipes#185]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

* **Ngx-pipes version:** 2.7.5

**Current behavior**
Using `filterBy` pipe will always return an array of type `any[]`, making it harder to use type suggestions.

**Expected behavior**
The filter should exclusively always return the same type as it's inputted.

**Minimal reproduction of the problem with instructions**
I'm trying to filter a set of `Node[]` by a specific id:
```
<div *ngFor="let node of component.nodes | filterBy:['id']: nodeId">
     <label>{{node.name}}</label>
</div>
```
This `Node` has several properties under it like `name:string`.  However, if you look at the type that gets returned by the filter, it will show that the node is now of type `any`.

**Please tell us about your environment:**
Not important

* **Angular version:** 11.1.0

* **Node (for AoT issues):** `node --version` =  v12.20.1

**Possibe Fix**
Looking at the [`filterBy` pipe code](https://github.com/danrevah/ngx-pipes/blob/master/src/ng-pipes/pipes/array/filter-by.ts), you'll see that there's 2 function overrides on top of the implementation:

```
transform(input: any[], props: Array<string>, search?: any, strict?: boolean): any[];
transform<T>(input: T, props: Array<string>, search?: any, strict?: boolean): T;
transform(input: any, props: Array<string>, search: any = '', strict: boolean = false): any {
   // Implementation
}
```
The problem is that when typescript goes through the declarations it goes from the top down until one that matches.  Since the first one is of `any[]`, it will match everything, hence it will always return `any[]` back.  An easy fix would be to move the typed declaration _above_ the `any[]` one, like so:
```
transform<T>(input: T, props: Array<string>, search?: any, strict?: boolean): T;
transform(input: any[], props: Array<string>, search?: any, strict?: boolean): any[];
transform(input: any, props: Array<string>, search: any = '', strict: boolean = false): any {
   // Implementation
}
```
This was tested on my local machine and it works wonderfully.  However, I feel like this problem affects more than just `filterBy` as many of the Array pipes do the same thing, like `flatten` or `intersection` or `groupBy` that doesn't even care about types at all.  I would offer to do a PR for this one, but I feel like there's a much bigger PR change that would need to be done.  I might address it at some point when I have the time but for the moment I wanted to bring this to your attention.

Love the work that's been done in this library and has definitely helped me out :)

Thanks.

**Comment by Adam-Michalski** [comment]
The same issue is with `orderBy` pipe, It changes type after transform to any[].
![image](https://user-images.githubusercontent.com/5684123/121866279-1078a180-ccff-11eb-8820-085f3dcf1026.png)
![image](https://user-images.githubusercontent.com/5684123/121866310-18384600-ccff-11eb-83f7-416c8a823cd3.png)
