### ISSUE TITLE
Is this repo actively being maintained?

### ISSUE THREAD

**Issue by pavankjadda** [danrevah/ngx-pipes#198]
I am using this repo in multiple projects and I see the last update in January 2020. I see many pull requests are open, is this actively being maintained?

**Comment by danrevah** [comment]
Yes, any major bugs will be taken care of.
In regards to new features, it depends.. I'm open for new ideas and PR's :).

**Comment by pavankjadda** [comment]
> Yes, any major bugs will be taken care of.
> 
> In regards to new features, it depends.. I'm open for new ideas and PR's :).

Thanks for the confirmation. I do see few issues where I can contribute. I will raise a PR with changes.
