### ISSUE TITLE
OrderBy? Any plans to Implement?

### ISSUE THREAD

**Issue by BallisticPain** [danrevah/ngx-pipes#20]
So I just stumbled across your library of pipes and it seems quite extensive and you seem to provide updates quite often. I wanted to reach out and see if you've considered an orderBy pipe, and if you have it already please forgive me for not recognizing it.

Thoughts?

**Comment by BallisticPain** [comment]
I'm looking / testing this currently: https://github.com/FuelInteractive/fuel-ui/blob/master/src/pipes/OrderBy/OrderBy.ts

**Comment by danrevah** [comment]
Looks like a good idea for a new pipe.
I will definitely add this one as well.

**Comment by danrevah** [comment]
There's a draft version under the `next` branch: https://github.com/danrevah/ngx-pipes/tree/next#orderby

https://github.com/danrevah/ngx-pipes/blob/next/src/app/pipes/array/order-by.ts

This will be merged in the following days into master & released on the next version.
Left todo: 
 * Performance test
 * Refactor a cleaner version

**Comment by danrevah** [comment]
Merged into master and released to version v1.3.1

Thanks.

**Comment by BallisticPain** [comment]
Fantastic work and quickly done... thanks!
