### ISSUE TITLE
Help: Webpack misconfiguration

### ISSUE THREAD

**Issue by TCMiranda** [danrevah/ngx-pipes#21]
Hey, 

I am trying to import the module on my app, but it is not working directly.
Currently I am building my project with webpack@~0 typesctipt@~2.0 and awesome-typescript-loader@~2

The error I get is:
![screenshot from 2017-01-29 12-11-31](https://cloud.githubusercontent.com/assets/10077439/22404631/15b2a1a6-e61c-11e6-83fc-09703164e3cf.png)

After some tests, I wonder if it is a path issue, but all the logs point to tslint.

Weird thing is that I use angular2-text-mask without any issues.
Trying to figure out what is wrong, I see that the ts config is pretty different.

https://github.com/text-mask/text-mask/blob/master/angular2/tsconfig.json

But I don't know yet what is causing this.
Any idea of where the error is coming from? The output is not so helpful also...

Thanks!

**Comment by TCMiranda** [comment]
Ooh OK, it is really something with *tslint*.

I disabled it entirely form my project and it works.
So I may leave this issue open, because I don't know if it is a bug or needs some fix. Unfortunately I just discovered that I am really outdated with typescript modules configuration :confused: 

Thanks!

**Comment by danrevah** [comment]
It's probably failing due to a rule in your `tslint.json` which isn't being followed by the `pipes.module.ts`.

Did you install `ngx-pipes` using npm ? your tslint shouldn't check for linting errors under the node_modules library.

**Comment by TCMiranda** [comment]
Yea now I excluded files outside my own project src, and everything works :tada: 

Yet tslint failed miserably :laughing: wonder if there are other problems here
Thanks for the help. Feels I can close this issue.
