### ISSUE TITLE
Custom delimiter support in 'groupBy' pipe while grouping multiple fields

### ISSUE THREAD

**Issue by shikhartanwar** [danrevah/ngx-pipes#22]
Custom delimiter as an additional optional argument in the `groupBy` pipe would be really helpful. Currently multiple fields are joined by `_` while grouping on multiple fields but `_` would not always be a unique delimiter and in that case the resultant map cannot be directly used.

**Comment by danrevah** [comment]
Did you mean that multiple fields are joined by underscore ("_")? and yes this makes sense if there's some properties with `_` it won't always be unique. 
I will add a custom delimiter as suggested.

**Comment by shikhartanwar** [comment]
Yes. I was referring to multiple fields getting joined by "_" only.

**Comment by danrevah** [comment]
I think that it might be better to also use `:` as default.
since "_" is commonly used as property name.
I will make the required adjustments.

**Comment by shikhartanwar** [comment]
Yes. That makes perfect sense. `:` or maybe `|` would be better options.

**Comment by danrevah** [comment]
Default has been changed to `|`.
I've also added an option to change the delimiter.

https://github.com/danrevah/ngx-pipes#groupby
Release version: v1.3.2
