### ISSUE TITLE
Angular Seed & ngx-pipes

### ISSUE THREAD

**Issue by Meistercoach83** [danrevah/ngx-pipes#23]
Hey there! 
I tried to integrate your pipes-module in the angular-seed from mgechev (https://github.com/mgechev/angular-seed/), but got some problems. I opened an issue for it: https://github.com/mgechev/angular-seed/issues/1794.

The last answer was helpful for me - now I can use it in dev. But could you do add this to your project: "The production build won't work out of the box because the author of the library hasn't disabled implicit any. Also, the package is not distributed with metadata.json files which means that AoT won't work neither"

**Comment by danrevah** [comment]
Hey @Meistercoach83,

Regarding the disabling of the implicit any, I've published a fixed version to v1.3.3.
Let me know if this fixes your problem.

I'm not entirely sure what needs to be done in order to make this library compliant with AoT.
I will find a time to dig into that to figure it out.

**Comment by Meistercoach83** [comment]
Hey! Thanks for your fast response. The updated package is ok. No errors are thrown any longer. I´ll give it a try.

**Comment by danrevah** [comment]
Cool. keep me updated if anything changes.
I'm keeping this issue open until i'll have time figure the AoT.

You are also welcome to send a pull-request if you already know what's missing.

**Comment by danrevah** [comment]
@Meistercoach83 
AoT with tree shaking is now working from v1.4.0 :1st_place_medal: 
Tested and working with angular-cli & webpack.

**Comment by danrevah** [comment]
I'm closing it for now let me know if this needs to be reopened.
