### ISSUE TITLE
Unable to use ngx-pipes with Ionic2

### ISSUE THREAD

**Issue by swaraasolutions** [danrevah/ngx-pipes#24]
Tried using ngx-pipes with ionic 2 the following error pops up all the time

`Module build failed: Error: ENOENT: no such file or directory, open 'node_modules\ngx-pipes\src\app\pipes\array\order-by.js.map' at Error (native)
`

Can you guide me to right direction?

Thanks

**Comment by danrevah** [comment]
I've changed the compiler recently #23 and that what caused this bug.
It should be fixed, try to install v1.4.1 and keep me updated if this fixed it.

Thanks for letting me know!

**Comment by swaraasolutions** [comment]
Great Thanks.

 

Let me have a look at it and get back to you.

 

Thanks for such a fast reply

 

Regards

 

Varun Varde

COO – Swaraa Solutions LLP

Contact: +91 – (0) 84606 13654

Email:  <mailto:varun@swaraasolutions.com> varun@swaraasolutions.com

**Comment by danrevah** [comment]
I'm closing this ticket for now, let me know if this needs to be reopened.
