### ISSUE TITLE
strictNullChecks errors

### ISSUE THREAD

**Issue by softsimon** [danrevah/ngx-pipes#29]
Getting a few errors from this lib when enabling strictNullChecks in tsconfig.json in my project.

ERROR in [..]/node_modules/ngx-pipes/src/app/pipes/object/invert-by.ts (7,23): Type 'null' is not assignable to type 'Function'.)

ERROR in [..]/node_modules/ngx-pipes/src/app/pipes/helpers/helpers.ts (39,6): An index expression argument must be of type 'string', 'number', 'symbol', or 'any'.)

**Comment by danrevah** [comment]
Thanks @softsimon !

I've merged your changes and it's now published to npm from version v1.4.4.
