### ISSUE TITLE
SystemJs

### ISSUE THREAD

**Issue by boris1690** [danrevah/ngx-pipes#32]
Hi, i cant config NGX-PPES, cause it show me the next error

http://localhost:3000/node_modules/ngx-pipes/src/app/pipes/array.js 404 (Not Found)
http://localhost:3000/node_modules/ngx-pipes/src/app/pipes/object.js 

i have this config in systemjs

 'ngx-pipes': {
            main: 'src/app/index.js',
            defaultExtension: 'js'
        }
in package;

**Comment by donaldinho** [comment]
just ran into the same issue.
The require statements in src/app/pipes.module.js
```var array_1 = require('./pipes/array');
var object_1 = require('./pipes/object');
var string_1 = require('./pipes/string');
var math_1 = require('./pipes/math');
var boolean_1 = require('./pipes/boolean');```
work when changed to
```var array_1 = require('./pipes/array/index');
var object_1 = require('./pipes/object/index');
var string_1 = require('./pipes/string/index');
var math_1 = require('./pipes/math/index');
var boolean_1 = require('./pipes/boolean/index');```
Although I don't want to have to edit the js to get this to work

**Comment by danrevah** [comment]
@donaldinho Thanks for letting me know what could solve it.
I've made the required changes and published to v1.4.5

Let me know if this fixed it.

**Comment by donaldinho** [comment]
Brilliant. Works for me now.
Thanks for fixing

**Comment by danrevah** [comment]
@donaldinho glad to hear!
@boris1690 Does that fixes your scenario as well?

**Comment by danrevah** [comment]
I'm closing it since it has been a week without a reply.. 
Let me know if this needs to be reopened.

Thanks.
