### ISSUE TITLE
Error when adding pipe to for loop

### ISSUE THREAD

**Issue by libin85** [danrevah/ngx-pipes#33]
I am getting an error when I add groupBy pipe on a for loop
`<div class="row" *ngFor="let tsk of tsks | groupBy: 'MilestoneName'">`

And the error that throws is
`Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.`

The array that I looping through is an Array

**Comment by danrevah** [comment]
GroupBy pipe returns an object of a key/value pair.
https://github.com/danrevah/ngx-pipes#groupby

From the reference:
 
```typescript
this.arrayObject = [
  {id: 1, elm: 'foo', value: 0}, 
  {id: 2, elm: 'bar', value: 1}, 
  {id: 3, elm: 'foo', value: 2}, 
  {id: 4, elm: 'foo', value: 2}
];
```

```html
<p>{{ arrayObject | groupBy: 'elm' }}</p> 
<!-- Output: "
{
 foo: [{id: 1, elm: 'foo', value: 0}, {id: 3, elm: 'foo', value: 2}, {id: 4, elm: 'foo', value: 2}], 
 bar: [{id: 2, elm: 'bar', value: 1}]
}" -->

```

NgFor expects an array.

You could use in addition to groupby the values pipe to get an array.

```html
<div class="row" *ngFor="let tsk of tsks | groupBy: 'MilestoneName' | values">
```

but it will drop the name of the group. 
What exactly are you trying to accomplish?

**Comment by libin85** [comment]
I call an api, which returns a json. I need to group the data and show that in a div.
`http.get('/api/Tasks').subscribe(result => {
            this.tsks = result.json() as Task[];
        });`
And I would like to group the data by Milestonename. I have about 1000 records, and I want to group all the records with a Milestone name. So  I would have a heading MilestoneOne, and then followed by all the records that has MilestoneOne as Milestonename underneath that. Hope I made sense

**Comment by danrevah** [comment]
You could use the `keys` pipe as follows, and do something like this:

```html
<div class="row" *ngFor="let milestoneName of tsks | groupBy: 'MilestoneName' | keys">
    <div>Group milestone name: {{milestoneName}}</div>

   <div class="row" *ngFor="let task of tsks[milestoneName]">
      <div>Task: {{task}}</div>
    </div>
</div>
```

**Comment by libin85** [comment]
The second loop throws the same error

**Comment by danrevah** [comment]
Can you provide an example of the `tsks` variable?

**Comment by danrevah** [comment]
Correct.. it was my mistake.
Try using the `pairs` pipe:
```html
<div class="row" *ngFor="let task of tsks | groupBy: 'MilestoneName' | pairs">
    <div>Group milestone name: {{task[0]}}</div>

   <div class="row" *ngFor="let task of tsks[1]">
      <div>Task: {{task}}</div>
   </div>
</div>
```

**Comment by libin85** [comment]
That still does not work. tsks is an array of object [ object, object, object....]
And each object is something like this
`
CompletedFlag: true
ProgressFlag: false
DueDate:"2014-10-02T13:12:37.027"
Signup: "2014-10-04T11:51:10.137"
ObMilestone: 001
ObTask: 119
AssignedToId: 0
Company: "ABC Corp"
Description: "Lorem Ipsum"
Favourite: null
FirstName: "Libin"
LastName: "J"
MilestoneName: "Blue"
OnboarderStatus: "Live"
Partner : null`

**Comment by danrevah** [comment]
Provide an example of the `tsk` as a JSON.

**Comment by danrevah** [comment]
The last piece of code that I wrote works perfectly for this data structure:
Make sure you copying it properly.

```typescript
tsks = [{
      CompletedFlag: true,
      ProgressFlag: false,
      DueDate:"2014-10-02T13:12:37.027",
      Signup: "2014-10-04T11:51:10.137",
      ObMilestone: 1,
      ObTask: 119,
      AssignedToId: 0,
      Company: "ABC Corp",
      Description: "Lorem Ipsum",
      Favourite: null,
      FirstName: "Libin",
      LastName: "J",
      MilestoneName: "Blue",
      OnboarderStatus: "Live",
      Partner : null
    },
    {
     CompletedFlag: true,
      ProgressFlag: false,
      DueDate:"2014-10-02T13:12:37.027",
      Signup: "2014-10-04T11:51:10.137",
      ObMilestone: 1,
      ObTask: 119,
      AssignedToId: 0,
      Company: "ABC Corp",
      Description: "Lorem Ipsum",
      Favourite: null,
      FirstName: "Libin",
      LastName: "J",
      MilestoneName: "Blue",
      OnboarderStatus: "Live",
      Partner : null
    }];
```

```html
<div class="row" *ngFor="let task of tsks | groupBy: 'MilestoneName' | pairs">
  <div>Group milestone name: {{task[0]}}</div>

  <div class="row" *ngFor="let t of task[1]">
    <div>Task: {{t.FirstName}}</div>
  </div>
</div>
```

**Comment by libin85** [comment]
@danrevah : Thanks heaps. That helped me to sort it.

**Comment by monogarm** [comment]
works fine
