### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by ibnuzaini** [danrevah/ngx-pipes#35]
when i use this one in ts file:
this.feeds = this.groupBy.transform(this.feeds, 'bp');
**it seems work great**
but whenever i apply to the html file:
{{group | groupBy: 'bp'}}
**ionic 2 shows blank page**

what i missed out?

**Comment by danrevah** [comment]
If you're getting it's probably throwing some error in the console.
Can you share this error ?

also did you add the `NgArrayPipesModule` or `NgPipesModule` to your module imports? 
https://github.com/danrevah/ngx-pipes#installation

does other pipes work for you?

**Comment by ibnuzaini** [comment]
1. This is the console say:
```
The pipe 'groupBy' could not be found ("

      <ion-item-divider sticky>
        <ion-label>[ERROR ->]
          {{group | groupBy: 'bp' | json}}
        </ion-label>
      </ion-item-divider>
"): CandidatePage@12:19 ; Zone: <root> ; Task: Promise.then ; Value: 
```

2. I use :
```
import { GroupByPipe } from 'ngx-pipes/src/app/pipes/array/group-by';
@Component({
...
  providers: [GroupByPipe]
})
```
3. Nope, i also try filter but also doesn't work
4. i try pipe `{{group | groupBy: 'bp' | json}}` but still no work

**Comment by danrevah** [comment]
You are not using it properly.. follow the instructions in: https://github.com/danrevah/ngx-pipes#installation
You MUST add `NgArrayPipesModule` or `NgPipesModule ` to your @NgModule `imports`
