### ISSUE TITLE
Convert my JSON Structure

### ISSUE THREAD

**Issue by ibnuzaini** [danrevah/ngx-pipes#36]
Please share idea using **ngx-pipes** to transform json structure  like this:
`[{"name" : "a", "class" : "red", "value" : "5"}, {"name" : "b", "class" : "red", "value" : "6"}, {"name" : "c", "class" : "blue", "value" : "7"}]`
to be:
```
[{"groupbyclass":
[{"class": "red"}, "person":
[{"name" : "a", "class" : "red", "value" : "5"}, {"name" : "b", "class" : "red", "value" : "6"}],
[{"class": "blue"}, "person": [{"name" : "c", "class" : "blue", "value" : "7"}]
}]
```
thanks in advance

**Comment by danrevah** [comment]
the object you're expecting is non-standard which means *ngx-pipes* doesn't have a magic pipe that could make this transformation.

You can however to achieve the following object:

`
  {
    "red": [{"name" : "a", "class" : "red", "value" : "5"}, {"name" : "b", "class" : "red", "value" : "6"}]
    "blue": [{"name" : "c", "class" : "blue", "value" : "7"}]
  }
`

by using `groupBy` with the class property.
