### ISSUE TITLE
Feature insert a character after every character

### ISSUE THREAD

**Issue by sarahsga** [danrevah/ngx-pipes#37]
For example: 
<p>{{'foobar' | insert: '-' }}</p> 
Should Output: 
"f-o-o-b-a-r"

**Comment by sarahsga** [comment]
Add step size option to the insert pipe
For example:
<p>{{'foobar with stepsize' | insert : '-' : 3 }}</p>

**Comment by danrevah** [comment]
Thanks @sarahsga for your contribution
Since I'm not sure if that filter could be useful for many use cases let's wait and see what the community has to say about it.

**Comment by beradrian** [comment]
I don't see its usefulness in many cases and even the name is not self explanatory. I would see it more as a combination of two filters {{s | split: 3 | concat: '#'}}
