### ISSUE TITLE
Module parse failed Error

### ISSUE THREAD

**Issue by santoshkt** [danrevah/ngx-pipes#43]
I included NgPipesModule in my NgModule imports but I am still getting below error. I'm using this with webpack. Not sure whats going on. Is anyone facing the same issue ?

```
ERROR in ./~/ngx-pipes/src/app/pipes.module.ts
Module parse failed: /Users/me/Projects/git/app-ui/node_modules/ngx-pipes/src/app/pipes.module.ts Unexpected character '@' (8:0)
You may need an appropriate loader to handle this file type.
| import {NgBooleanPipesModule} from './pipes/boolean/index';
|
| @NgModule({
|   declarations: [],
|   imports: [],
 @ ./~/ngx-pipes/src/app/index.js 5:9-34
 @ ./src/main/webapp/app/vendor.ts
 @ dll vendor
```

**Comment by danrevah** [comment]
Can you show your `webpack.config` file part of the `ts` loader?

**Comment by santoshkt** [comment]
```
                {
                    test: /\.ts$/,
                    loaders: [
                        'angular2-template-loader',
                        'awesome-typescript-loader'
                    ],
                    exclude: ['node_modules/generator-jhipster']
                },
```

Please let me know if you need any other information

**Comment by danrevah** [comment]
Looks like a common misconfiguration issue with ng2 libs.
Check this topic: https://github.com/jkuri/ng2-datepicker/issues/136

Let me know if that helped.

**Comment by santoshkt** [comment]
Thank you for checking a solution for me. I tried the exact solution as mentioned there before posting this question :)

When I changed to

```
{
                    test: /\.ts$/,
                    loaders: [
                        'angular2-template-loader',
                        'awesome-typescript-loader'
                    ],
                    exclude: [/node_modules\/(?!(ng2-.+|ngx-.+))/]
                },
```

I got errors as below.

```
ERROR in ./~/reflect-metadata/Reflect.ts
Module parse failed: /myfolder/git/myproject/node_modules/reflect-metadata/Reflect.ts Unexpected token (15:10)
You may need an appropriate loader to handle this file type.
| and limitations under the License.
| ***************************************************************************** */
| namespace Reflect {
|     "use strict";
|
 @ ./src/main/webapp/app/polyfills.ts 4:0-35
```

I was n't sure what this errors are for, so I din't go with that solution. I'm new to TS and ng2.

**Comment by santoshkt** [comment]
- Without adding ngx-pipes, if I remove excludes section, compile is successful. 
- Adding ngx-pipes, nothing in excludes section, compile fails. I get complete node_modules is excluded if nothing is mentioned by default. 
- From the example you mentioned, I believe the regex excludes libraries that do not start with ng2 or ngx. So as per original exclude section having only generator-jhipster, ngx-pipes should still be included for compile.

**Comment by santoshkt** [comment]
I went ahead with `angular-pipes` with no problems...

**Comment by danrevah** [comment]
@santoshkt Thanks for letting me know! I've made a few adjusments and upgraded the infrastructure to Angular 4.

Since I wasn't able to restore that error. Can you upload a seed project that's failing with `ngx-pipes` or to give me detailed explanation on how you managed to get this error? 

Thanks

**Comment by santoshkt** [comment]
I created a sample project for you to try - https://github.com/santoshkt/ngx-pipes-test

run 'yarn install' and that should reproduce the error. Let me know if you need any other information. 

I saw you are considering to merge with `angular-pipes`. Do you know if there is anything mutually exclusive in the projects at this time ? A quick glance makes me feel both are almost same.
