### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Alb0za** [danrevah/ngx-pipes#44]
> ERROR in C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/node_modules/@angular/core/src/errors.d.ts (9,33): Initializers are not allowed in ambient contexts.
C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/node_modules/@angular/core/src/errors.d.ts (10,43): Initializers are not allowed in ambient contexts.
C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/node_modules/@angular/core/src/errors.d.ts (11,42): Initializers are not allowed in ambient contexts.
C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/node_modules/@angular/core/src/errors.d.ts (12,43): Initializers are not allowed in ambient contexts.
C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/node_modules/@angular/core/src/errors.d.ts (13,35): Initializers are not allowed in ambient contexts.

ERROR in C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/node_modules/@angular/core/src/animation/dsl.d.ts (34,33): Initializers are not allowed in ambient contexts.

ERROR in C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/node_modules/@angular/core/src/animation/animation_metadata_wrapped.d.ts (12,33): Initializers are not allowed in ambient contexts.

ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/node_modules/@angular/core/core.d.ts, resolving symbol NgPipesModule in C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/src/app/index.d.ts, resolving symbol NgPipesModule in C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/src/app/index.d.ts

> @angular/cli: 1.0.0
node: 7.6.0
os: win32 x64
@angular/cli: 1.0.0
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/compiler-cli: 2.4.10

`

I am having this issue right now and don't know why using this version "ngx-pipes": "^1.4.6", Can you help me out.

**Comment by danrevah** [comment]
Can you try updating to 1.5.2 and let me know if this continues?

**Comment by Alb0za** [comment]
I upgraded to 1.5.2, and still have the problem.

>  "devDependencies": {
    "@angular/cli": "^1.0.0-beta.28.3",
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "^2.0.40",
    "@types/node": "^6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }

**Comment by danrevah** [comment]
looks like your typescript version is outdated try using: "typescript": "~2.2.0"

**Comment by Alb0za** [comment]
> ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/node_modules/@angular/core/core.d.ts, resolving symbol NgPipesModule in C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/src/app/index.d.ts, resolving symbol NgPipesModule in C:/Users/genti/Desktop/New folder/frontend_software/node_modules/ngx-pipes/src/app/index.d.ts


still this issue with the latest typescript

**Comment by Alb0za** [comment]
I removed the node_modules and made a clean install with 
"typescript": "^2.2.0" and "ngx-pipes": "^1.5.2",, 

still having the same issue

**Comment by danrevah** [comment]
Looks like it might be related to this issue: https://github.com/angular/angular/issues/15767
Since the update to Angular 4

**Comment by Alb0za** [comment]
yes probably, so know what to do ? just wait for a solution from the angular team ?

**Comment by danrevah** [comment]
Im trying to find a workaround. Will keep you updated.

**Comment by danrevah** [comment]
Is there anything stopping you from updating to Angular 4.0.1 ? 
I managed to restore this bug locally while using old angular-cli package and angular 2.4.8.

It worked with the following dependencies: 

```json
  "dependencies": {
    "ngx-pipes": "~1.5.4",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
```

**Comment by danrevah** [comment]
Related to #46, it's a dependencies issues. 
Update to the official release of `@angular/cli: 1.0.0`, also a good idea would be to update to Angular 4.
