### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by ethanward91** [danrevah/ngx-pipes#45]
I'm getting this warning which seems to be preventing the package from getting bundled up.

> WARNING in ./~/ngx-pipes/~/@angular/core/@angular/core.es5.js
> 5886:15-102 Critical dependency: the request of a dependency is an expression

I'm using webpack, so this could be something to do with me not setting that up correctly, but I'm only getting this when I include ngx-pipes. That seems to be the only one that is throwing this warning.

**Comment by danrevah** [comment]
Seems like an Angular 4 misconfiguration. 
What version of Angular are you using?

Check out this answer: https://github.com/AngularClass/angular2-webpack-starter/issues/993#issuecomment-283423040

**Comment by danrevah** [comment]
Closing as there no answer for the past 2 weeks.
Let me know if you still need help.

**Comment by Albosonic** [comment]
Also having this error. can't figure out why. But on the bright side everything seems to work fine.

**Comment by danrevah** [comment]
@Albosonic Can you upload your `package.json` file?

**Comment by claudiuconstantin** [comment]
See https://github.com/AngularClass/angular-starter/issues/993#issuecomment-287290980
