### ISSUE TITLE
OrderBy nested object properties, where property is undefined

### ISSUE THREAD

**Issue by dearibujar** [danrevah/ngx-pipes#49]
When i use OrderBy pipe to order my array of objects, depending on a nested object property , which can also be undefined at one or another child of object, i get a strange result. I would expect the result where every object (User), which has the property i orderBy, would be listed before users that dont have that property, but what i get is some users with that propety are at the top, then i get some users with that property undefined or empty stringm then again users which have that property.
How are undefined, empty string or null compared to strings?

**Comment by danrevah** [comment]
Please provide additional information such as: current input/output and expected output.

**Comment by dearibujar** [comment]
`*ngFor="let user of users | orderBy : app_metadata.slog.ngt_group_id ;`
Some of the users, dont have 'app_metadata' , some dont have 'slog' and some dont have 'ngt_group_id'.

Output:
Name                 ngt_group_id
John Doe
Arjen Robben            1
R.Lewandowski          1
Manuel Neuer            
Tiago Alcantara         15
Franc Ribery                


What i would like to achieve is

Name                        ngt_group_id
Tiago Alcantara              15
Arjen Robben                   1
R.Lewandowski                 1
John Doe                       
Franc Ribery             
Manuel Neuer

**Comment by danrevah** [comment]
I didn't support such behaviour yet, but since it makes sense to ignore the undefined values and it was an easy fix.

Just update to `ngx-pipes: v1.5.9`.
if you want to order this by reverse order then just add prefix of `-`

for ex:
```html
<div *ngFor="let user of users | orderBy: -app_metadata.slog.ngt_group_id></div>
```

**Comment by dearibujar** [comment]
Thank you :D this fixed my issue with undefined. My issue with empty objects exists still but i can handle it in another way.

**Comment by danrevah** [comment]
Not quite sure what you mean by empty objects, can you provide an example for this as well ?

**Comment by dearibujar** [comment]
Sorry what i wanted to say is if for example `{name:'' }`, maybe it would be nice if that object is shifted even at the end or at the start of the array

**Comment by danrevah** [comment]
Sorry if I'm not quite catching what you mean but why would it be shifted?
If you're sorting by `-app_metadata.slog.ngt_group_id` only ?

If you can provide an example input/output and an expected behaviour I might as well add this beavhiour if it is logical :)

**Comment by dearibujar** [comment]
What i mean is if i am sorting by -app_metadata.slog.ngt_group_id and if ngt_group_id has the value of an empty string , it would be nice if it is handled like the undefined, because right now it stays always top no metter if you are sorting by ascending or descending

**Comment by danrevah** [comment]
Makes sense.. `v.1.5.10` Enjoy.

Thanks!

**Comment by dearibujar** [comment]
Nice :D thank you !
