### ISSUE TITLE
Distance pipe, miles or km for converting km to meters etc.

### ISSUE THREAD

**Issue by efstathiosntonas** [danrevah/ngx-pipes#50]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

Hi, it would be nice to have a pipe to convert km to meters  and miles to yards || feet when distance value starts with `0`.

see attached image

![distance_pipe](https://cloud.githubusercontent.com/assets/717975/25554262/845f80f0-2cd1-11e7-9022-3e6e030dd54d.png)

**Comment by danrevah** [comment]
Can't find it's usefulness due to the lack of community response
