### ISSUE TITLE
unique pipe is not supporting objects

### ISSUE THREAD

**Issue by Sevensnake** [danrevah/ngx-pipes#51]
If you have an object with multiply object and one object has the same value over and over but the other object have different values this does not work. As you see ETF will still repeat itself.
Is there a way I can use this with a specific object. {{Name | unique   }} << like so.

example.

`[{"D":416,"Name":"ETF Trust","PortFiling":false,"SeriesID":1256,"esName":"LP ETF","PortFiling":false},{"ID":416,"Name":"ETF Trust","Filing":false,"SeriesID":1108,"esName":"Equal Sector Weight ETF","PortFiling":false},{"D":416,"Name":"ETF Trust","Filing":false,"ID":998,"esName":"CRealty Majors ETF","PortFiling":false},{"ID":416,"CIKName":"ETF Trust","Filing":false,"ID":1123,"esName":"Global}]`

**Comment by danrevah** [comment]
It wasn't suppose to work with objects, altho it might be a nice feature to have.

Pull request for this are welcomed.. If not I will try to find a time for this as well.

**Comment by danrevah** [comment]
@Sevensnake  Released an imporvment in `v1.6.0` take a look at #58
