### ISSUE TITLE
unique filter is not working on objects

### ISSUE THREAD

**Issue by anilkumar007** [danrevah/ngx-pipes#55]
i have an array in app.component.ts as
`
 this.demoarray = [{facility_category_id: 2, facility_category_name: 'test1'}, {facility_category_id: 3, facility_category_name: 'test2'}, {facility_category_id: 3, facility_category_name: 'test2'}]
`
In my html page the code 
i tried in 2 ways
`
 <ion-item *ngFor="let item of items | unique: 'item.facility_category_name'">
        <h4>{{item.facility_category_name}}</h4>
  </ion-item>
<ion-item *ngFor="let item of items | unique: 'facility_category_name'">
        <h4>{{item.facility_category_name}}</h4>
  </ion-item>
`

But unique filter is still not working 
Please help me to fix these issue

**Comment by danrevah** [comment]
unique pipe is currently not supported for objects.
a pull-request is welcome.

**Comment by anilkumar007** [comment]
Thanks @danrevah  for the reply .. is there any alternative way to fix these issue?

**Comment by danrevah** [comment]
Released an imporvment in `v1.6.0` take a look at #58
