### ISSUE TITLE
Safe URLs

### ISSUE THREAD

**Issue by beradrian** [danrevah/ngx-pipes#59]
Create pipes for sanitizing URLs.

**Comment by danrevah** [comment]
I'm not sure about those pipes, they could be a bit risky.

Looks like it can exposes XSS issues: https://angular.io/docs/ts/latest/api/platform-browser/index/DomSanitizer-class.html

Not quite sure why this needs to be added to `ngx-pipes` it can cause confusion and let expose vulnerabilities.
