### ISSUE TITLE
Returns relative number to thousand symbol

### ISSUE THREAD

**Issue by calebeaires** [danrevah/ngx-pipes#60]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```
Would be great if there is an feature that transform number into a relative values, like ``bytes`` already do with a unit symbol.
```javascript
{{ 1000 | bytes }} <!-- Output: "1 k" -->
{{ 10000 | bytes }} <!-- Output: "10 k" -->
{{ 12000 | bytes }} <!-- Output: "12 k" -->
```

**Comment by danrevah** [comment]
Can you explain more on what exactly are you looking for this filter to be doing? its looks like you only to concat a string to the end of the number?

**Comment by calebeaires** [comment]
If you want show numbers on a table that count nunbers of products. I want show relative numbers: 

| Seeds  | amount | relative amount |
| ------------- | ------------- | ------------- |
| rice  | 123000  | 123 k  |
| Bean  | 1000  | 1k  |

**Comment by danrevah** [comment]
I really can't see it's usefulness.. you can just do 

```html
<div class="number">{{ (num / 100) | floor }}k</div>
```

**Comment by calebeaires** [comment]
It works, very thanks!
