### ISSUE TITLE
Could you enhancement feature pipe for date

### ISSUE THREAD

**Issue by jason-answer** [danrevah/ngx-pipes#64]
Hi, 
Your code is cool, could you enhance feature pipe for date? e.g: date format, json data format. date sort......

**Comment by danrevah** [comment]
In Angular, you already have a built-in pipe for date format and json data: https://angular.io/api/common/DatePipe
https://angular.io/api/common/JsonPipe

`ngx-pipes` also supports sort by date you can just use `orderBy` pipe.
