### ISSUE TITLE
FilterBy Empty Field

### ISSUE THREAD

**Issue by Meistercoach83** [danrevah/ngx-pipes#65]
Hi!

is it possible to filter an array to get only the array members where a given field is empty or even undefined?

**Comment by Meistercoach83** [comment]
@danrevah any answer?

**Comment by danrevah** [comment]
Hey @Meistercoach83,

Thanks for your feedback.

This feature is currently unsupported.
I don't think it's even going to be supported in the future.

Let's see if the community has something to say about this, if it's something common I might consider adding this to `ngx-pipes`.

**Comment by bujardeari** [comment]
I would like to filter by a field that not every object has. Is this  possible?

**Comment by klocus** [comment]
It would be nice if you could enter `null` as a search parameter. But you can get around this by using the "groupBy" pipe:

```
<div ngFor="let article of (articleArray | groupBy: 'category').null">
    <span>{{ article.title }}</span>
</div>
```

Pipe "groupBy" will create an object `null` with an array of articles where property `category` is empty :)
