### ISSUE TITLE
Array orderBy sort problem

### ISSUE THREAD

**Issue by PuriaRad** [danrevah/ngx-pipes#66]
Hello
I'm using orderBy pipe in my application, and I found out it first sorts 6 digits together then 5 digits and so on. I don't know it's a bug or I'm doing something wrong. 

For example it's something like this:

before orderBy => {'150000','120000','30000','50000','25000'}
after orderBy => {'120000','150000','25000','30000','50000'}

What I expected => {'25000','30000','50000','120000','150000'}

Please let me know how to fix this, and thank you for your amazing module.

Ngx-pipes version:1.6.2
@angular/compiler-cli: 4.2.4
@angular/cli: 1.3.0-rc.1
Angular version:** 4.2.4
npm version :5.3.0
node version: 6.11.1

**Comment by danrevah** [comment]
It looks like your array contain string value? am I correct?

If it's a string value that would explain the result you are getting, it's sorting it by alphanumeric order.
You should really convert those values to integer before using orderBy.

Try to convert them first to integers and let me know if that helped.

```typescript
this.arr = arr.map(v => parseInt(v));
```
