### ISSUE TITLE
Bytes pipe

### ISSUE THREAD

**Issue by stumpyfr** [danrevah/ngx-pipes#67]
Hi,

For the bytes pipe, it's would be better to use 1024 and not 1000 for the conversion.
It's probably more common everywhere to use 1024, 1000 is valid in case of you suffix the result with a lower case k/m/g.

`1000 bytes => 1kB`
`1024 bytes => 1KB`

Reference: https://en.wikipedia.org/wiki/Kilobyte

**Comment by danrevah** [comment]
I agree.. I'll try to find a time and to push an update for this.

Thanks.

**Comment by danrevah** [comment]
It was now released in v1.6.5.
