### ISSUE TITLE
filterBy compile time errors, no runtime errors

### ISSUE THREAD

**Issue by brianthomps** [danrevah/ngx-pipes#69]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X ] Other
```

* **Ngx-pipes version:** 1.6.4

**Current behavior**
First of all, thanks for providing such a great library.  I am using the `filterBy` pipe, which is working fine.  I have only imported the `NgArrayPipesModule`.  I am using webpack to bundle the source, and am seeing some errors in the console, but the application runs just fine...  The only concern is that these console errors will come back to haunt me when the code enters the CI/CD pipeline.  They are as follows:

```[at-loader] Checking finished with 2 errors
[at-loader] ./node_modules/ngx-pipes/src/app/pipes/array/unique.ts:13:53
    TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

[at-loader] ./node_modules/ngx-pipes/src/app/pipes/math/bytes.ts:20:70
    TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.
```

`at-loader` is "awesome-typescript-loader", which is basically just a loader used by webpack for typescript files.  So the errors occur at compile time, but there's nothing in the browser's console during run-time and the behavior of the pipe (and application overall) is working as expected.  Any idea how this could be remedied?

**Expected behavior**
I expect that there are no errors during compile time, given that everything has been implemented properly.

**Minimal reproduction of the problem with instructions**
I have a large project, but it started from a seed project; might provide these instructions if needed.

**Please tell us about your environment:**

OS: Windows 7
IDE: Microsoft VS Code
Package manager: NPM
HTTP server: Nginx

* **Angular version:** 4.2.4

**Comment by danrevah** [comment]
Fixed in v1.6.5
