### ISSUE TITLE
published source confuses angular-cli which causes "duplicate" code in output bundle

### ISSUE THREAD

**Issue by e-cloud** [danrevah/ngx-pipes#70]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

* **Ngx-pipes version:** 1.5.X

**Current behavior**
If i declare a specific pipe in a component's provider, and with lazyload routing, angular-cli will resolve to target pipe to the published src folder. Beside, i use other pipes with ngModule imports in other module, and it will be resolve to the dist bundle. Therefore, "duplicate" code are bundled.

I believe that's the inproper published bundle of ngx-pipes but not angular-cli.

**Expected behavior**
No "duplicate" code in bundle

**Minimal reproduction of the problem with instructions**

https://github.com/e-cloud/demo-repo-for-various-issues/tree/ngx-pipes%2370/cli-test

**Please tell us about your environment:**

* **Angular version:** 4.3.6

* **Node (for AoT issues):** `node --version` =   7.10

**Comment by danrevah** [comment]
Fixed as part of bundling changed from verison `v2.0.0`.
