### ISSUE TITLE
Formatting byte pipe

### ISSUE THREAD

**Issue by Robouste** [danrevah/ngx-pipes#73]
Sometimes, when using the byte pipe, I got something like 120.12345698 KB. It would be nice to have a parameter (like the pipe number) to format the value.

By the way, very nice module.

**Comment by danrevah** [comment]
There is a precision parameter which is not documented, you can pass as an integer.

```html
<p>{{ 10 | bytes: 2 }}</p> 
```

**Comment by Robouste** [comment]
Thanks :)
