### ISSUE TITLE
filterBy strict:true , results blank when search string is empty

### ISSUE THREAD

**Issue by bujardeari** [danrevah/ngx-pipes#74]
* **Ngx-pipes version:** 1.6.5

**Current behavior**
I have a search input which the value of which I use as search string for filterBy pipe.
When using filterBy pipe with strict option true , when the input is empty ,all the results are gone, only when i write some value that exists i get exactly that otherwise its blank.

**Expected behavior**
I would like it to show all results when search string is empty string.

**Comment by danrevah** [comment]
Strict mode means it will use `===` equal operator in order to find that row exactly.
If you want it to show all results when you search with an empty string then just remove the strict mode.

**Comment by bujardeari** [comment]
I found a workaround for my problem like this
` <input class="" type="text" placeholder="Søk" class="form-control " [(ngModel)]=" (keyup)="isEmpty()">`
and 
`isEmpty()=>{
if (this.searchString === "") {
            this.searchString = null
        }
}`

**Comment by danrevah** [comment]
Great.

**Comment by diosney** [comment]
For future reference, I solved this by:

```
filterByImpure:['result']:(filterToggleGroup.value === 'all')?undefined:filterToggleGroup.value.toUpperCase()
```

So, by returning `undefined` in the pipe search param (the 2nd argument), it un-filters all.
