### ISSUE TITLE
orderBy pipe doesn't allow for numerical sorting

### ISSUE THREAD

**Issue by atothe** [danrevah/ngx-pipes#75]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
```

* **Ngx-pipes version:** 1.6.5

**Current behavior**
orderBy pipe doesn't allow for numerical sorting

**Expected behavior**
Wanting the orderBy pipe to allow for numerical sorting

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **Node (for AoT issues):** `node --version` =   7.8.0

**Comment by danrevah** [comment]
Can you provide an example of what is not working for you?

**Comment by danrevah** [comment]
It does sort by numerical values. The problem is with your data..
`label` property is a string instead of an integer.

try to map it with something like this

```typescript
places = places.map((elm) => {
    const label = parseInt(elm.label);
    return {...elm, label};
});
```
