### ISSUE TITLE
Using groupBy in combination with ngFor does not work

### ISSUE THREAD

**Issue by Juchar** [danrevah/ngx-pipes#76]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
```

**Ngx-pipes version** 
1.6.5

**Current behavior**

Using the `groupBy` pipe together with `ngFor` for grouping objects and iterating over them.

I get the following error:

> ERROR Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.
>     at NgForOf.webpackJsonp.../../../common/@angular/common.es5.js.NgForOf.ngOnChanges (common.es5.js:1681)
>     at checkAndUpdateDirectiveInline (core.es5.js:10853)
>     at checkAndUpdateNodeInline (core.es5.js:12357)
>     at checkAndUpdateNode (core.es5.js:12296)
>     at debugCheckAndUpdateNode (core.es5.js:13160)
>     at debugCheckDirectivesFn (core.es5.js:13101)
>     at Object.View_AppComponent_0._co [as updateDirectives] (AppComponent.html:30)
>     at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13086)
>     at checkAndUpdateView (core.es5.js:12263)
>     at callViewAction (core.es5.js:12631)

**Expected behavior**
No error.

**Minimal reproduction of the problem with instructions**

inside **app.component.ts**
```
export class SampleObject {
  name: string;
  value: number;
  group: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
    sampleObjects: SampleObject[] = [
        {name: 'Test 1', value: 1, group: 'Group 1'},
        {name: 'Test 2', value: 2, group: 'Group 1'},
        {name: 'Test 3', value: 3, group: 'Group 1'},
        {name: 'Test 4', value: 4, group: 'Group 2'}
      ];
}
```

inside **app.component.html**
```
<ng-template ngFor let-grouped [ngForOf]="sampleObjects | groupBy: 'group'">
    <span>{{grouped.key}}</span>
    <ng-template ngFor let-object [ngForOf]="grouped.value">
        <span>{{object.name}} - {{object.value}}</span>
    </ng-template>
</ng-template>
```

**Please tell us about your environment:**
Windows, Intellij IDEA, npm

**Angular version:**
4.2.4

**Comment by nosTa1337** [comment]
same here

**Comment by danrevah** [comment]
NgFor expects an Array, while `groupBy` returns an object.
Take a look at my answer here: https://github.com/danrevah/ngx-pipes/issues/33#issuecomment-284863058

**Comment by danrevah** [comment]
Closing for now, let me know if something isn't clear and i'll reopen this.
