### ISSUE TITLE
Arrays shuffle with two elements

### ISSUE THREAD

**Issue by shalevshalit** [danrevah/ngx-pipes#77]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

* **Ngx-pipes version:** 1.6.5

**Current behavior**
Array shuffle doesn't work for two elements

**Expected behavior**
Should shuffle two element in 50% change each state [1,2] and [2,1]

**Minimal reproduction of the problem with instructions**
1. import {ShufflePipe} from 'ngx-pipes/esm/pipes/array/shuffle';
2. constructor(private shuffle: ShufflePipe)
3. this.shuffle.transform([1,2])

**Please tell us about your environment:**
macOS

* **Angular version:** 4.1.0

**Comment by danrevah** [comment]
Thanks for letting me know! 
I've fixed it and pushed a new version to npm `v1.6.6`.
