### ISSUE TITLE
Reqeust for a duplicate pipe

### ISSUE THREAD

**Issue by bujardeari** [danrevah/ngx-pipes#79]
This is not an issue , its more a question or request to have a pipe like the unique pipe , which returns only distinct mebmers but also show the number of dplicates for each member.

**Comment by danrevah** [comment]
Hey @bujardeari,

I can't seem to find a common use for such a pipe.
Since Ngx-Pipes is a collection of commonly useful pipes, let's wait and see if the community here thinks it's a good idea to add such a pipe.

Thanks.

**Comment by bujardeari** [comment]
I changed my data structure to avoid using a pipe for this, but the reason i needed it was a shopping cart, where i had a product object for each quantity of a product, but on the cart view i liked to show only one line of the product with the number of duplicate as quantity.
However it would be nice to have something like this if there are others who need it to.
