### ISSUE TITLE
Request: readable boolean pipe

### ISSUE THREAD

**Issue by kelvindart** [danrevah/ngx-pipes#80]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

* **Ngx-pipes version:** 1.6.6

**Current behavior**
At the moment, there is no default Angular pipe to convert a boolean (or, indeed, a truthy value) into a human-friendly value. It displays 'true' or 'false'. Sometimes, there may be instances where you want to display a different string based on the boolean value.

**Expected behavior**
I wondered whether it is worth having a pipe which allows for this. E.g. truthy: "Yes" and falsy: "No" for instance. You can have configurable values should you want something else to display, e.g.

    transform(value: any, truthyValue: string = 'true', falsyValue: string = 'false') {
      ...
    }

**Usage:**

    {{ myBool | readableBool }} // displays "true" or "false"

OR:

    {{ myBool | readableBool: 'Oui': 'Non' }} // displays "Oui" or "Non"

**Minimal reproduction of the problem with instructions:**

N/A

**Please tell us about your environment:**
N/A

* **Angular version:** 2.0.X

* **Node (for AoT issues):** `node --version` = 8.8.1

I am happy to look at implementing this if you believe it is desirable for `ngx-pipes`?  If so, should it fall within the Strings module, or Boolean?

**Comment by Albejr** [comment]
`<span>{{ item.Ativo ? 'Sim' : 'Não' }}</span>`

Very simple and does not require create pipe.
