### ISSUE TITLE
New Pipes Request which are misisng in ngx-pipes

### ISSUE THREAD

**Issue by JinnaBalu** [danrevah/ngx-pipes#85]
1. Converting a User Name to Short Profile User Name Pipe - 
Jinna Balu - JB
Jinna S Balu - JB
Jinna - JI

This is used for Profiles Names to show instead of the Image

Something Like This 
![image](https://user-images.githubusercontent.com/11784253/32511688-852b1018-c41a-11e7-8420-5527b7641e99.png)

2. Converting number to Short Scale Number 
1000 - 1.0K
8600000 - 8.6M
500600000 - 1.5B
1100000000000 - 1.1T

This is used in case ok long length number just like views downloads and count in short number to make use of the space.

If this this is accaptable to do I am done with the task. I used ngx-pipes in my project I felt like these are missing so I have created and raised a PR

**Comment by danrevah** [comment]
Let's wait for the community response to see what they think about it and if such a feature seems to be necessary.

**Comment by felladrin** [comment]
I endorse adding these pipes. I'd make a good use of them too.

**Comment by Albejr** [comment]
Initials & Value Avatar
[HaithemMosbahi/ngx-avatar](https://github.com/HaithemMosbahi/ngx-avatar)

**Comment by danrevah** [comment]
I know it's been a while since this, but would you like to fix the conflict of your pull-request or make a new one with this feature?

**Comment by danrevah** [comment]
@JinnaBalu I know it's been a while since this, but would you like to fix the conflict of your pull-request or make a new one with this feature?

Or, does anyone else wants to make a PR for this?

**Comment by danrevah** [comment]
1. is not going to be implemented
2. implemented as `bytes` pipes
