### ISSUE TITLE
Unexpected value NgPipesModule when AOT building with Angular 5

### ISSUE THREAD

**Issue by sconix** [danrevah/ngx-pipes#86]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

* **Ngx-pipes version:** 2.0.0

**Current behavior**
Running 'ng build --aot' results in the error: Unexpected value NgPipesModule....
Angular cli version: 1.5.0

**Expected behavior**
To get successful build.

**Minimal reproduction of the problem with instructions**
Just include NgPipesModule in a fresh angular-cli project.

* **Angular version:** 5.0.0

* **Node (for AoT issues):** `node --version` =   8.7.0

**Comment by danrevah** [comment]
It should work from now, just upgrade to `v2.0.1`.

Let me know if there's any issues, there has been a bundling changes in this version.

Thanks for the update.
