### ISSUE TITLE
Create a new pipe to fill arrays of numbers.

### ISSUE THREAD

**Issue by Albejr** [danrevah/ngx-pipes#88]
**I'm submitting a ...**
```
[   ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
```
[Pull request #87](https://github.com/danrevah/ngx-pipes/pull/87)

* **Ngx-pipes version:** 2.0.1

**Comment by danrevah** [comment]
Deployed to version `v2.0.1`
