### ISSUE TITLE
Not part of compilation output

### ISSUE THREAD

**Issue by Meistercoach83** [danrevah/ngx-pipes#89]
Hi! I´m getting the following error when I try to start the "ng serve" command:

> node_modules\ngx-pipes\src\app\pipes\helpers\helpers.ts is not part of the compilation output. Please check the other error messages for details.

There are no other error messages.

ngx-pipes: 1.7.0,
angular/cli: 1.5.0,
Angular-Version: 5.0.0

**Comment by danrevah** [comment]
Can you try updating to version `2.0.1` and check if this still happens?

Notice that `2.0.1` had a breaking change in the directory structure
Instead of `ngx-pipes/src/app/pipes/...` we removed the `app` folder so it's just: `ngx-pipes/src/pipes/...`.

Thanks.

**Comment by Meistercoach83** [comment]
Can be closed.

Other question: Is it possible to search this object for the assignedCategory 'main'?
FilterBy doesn´t work ....

> article = {
>    title: 'Test',
>    'assignedCategories': [
>      '12345': 'seniors',
>     '5678': 'main'
>    ]
> }

**Comment by danrevah** [comment]
Can you explain what exactly you are trying to do what output are you expecting?

**Comment by Meistercoach83** [comment]
I save the categories, which are associated to an article in the array 'assignedCategories' and I want to filter these assignedCategories. For example I want to get all Articles which have a assignedCategory 'seniors'

**Comment by danrevah** [comment]
I would need you to provide an expected input & output

**Comment by danrevah** [comment]
Closed since the topic has been resolved.

**Comment by himajaM** [comment]
ERROR in ./node_modules/ngx-uploader/src/classes/index.ts
Module build failed: Error: D:\demo\node_modules\ngx-uploader\src\classes\index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (D:\rndtc\rndtc\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:624:23)
    at plugin.done.then (D:\rndtc\rndtc\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./node_modules/ngx-uploader/ngx-uploader.js 6:0-86
 @ ./src/app/modules/consult/consult-job/consult-job.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Solution for my above error pls !!!!!!!** 

**Angular CLI: 1.5.2
Node: 7.4.0
OS: win32 x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.5.2
@angular/typescript: 2.0.0-5d0e199
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.2
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1**

**Comment by Meistercoach83** [comment]
> \ngx-uploader\src\classes\index.ts is not part of the compilation output. 

I don´t think the ngx-pipes throw the error above :-)

**Comment by danrevah** [comment]
@himajaM have you tried updating to 2.0.X ?

**Comment by himajaM** [comment]
@Meistercoach83  @danrevah  Thank you... it was solved after deleting my node_modules folder and re installed

**Comment by himajaM** [comment]
![33057873-e37d494a-ceb2-11e7-8373-0f4fbe323976](https://user-images.githubusercontent.com/26132177/33075335-19e1fcb0-ceef-11e7-868f-e7f7985640ae.png)

Hi Manish,

Recently i was
 upgraded my code from angular 2 to angular 5 i.e latest version and finding an error as below with wijmo 5: 

Angular CLI: 1.5.3
Node: 7.4.0
OS: win32 x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.5.3
@angular/typescript: 2.0.0-5d0e199
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.3
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1

Example : 
<wj-flex-grid-column [header]="'Years'" [binding]="'Years'" [width]="80" [format]="'d'">
<template wjFlexGridCellTemplate [cellType]="'Cell'" let-cell="cell">
<a (click)="routeToJob('jobDetails',cell.item.Id, cell.item.JobViewedOn)">
{{cell.item.TaxYears}}
</a>
</template> 
</wj-flex-grid-column>

**Comment by caseyPav** [comment]
Template is deprecated and let- will no longer work on it- change all <template> to <ng-template> and that will resolve the error
