### ISSUE TITLE
RangePipe not identified.

### ISSUE THREAD

**Issue by Albejr** [danrevah/ngx-pipes#90]
**I'm submitting a ...**
```
[ X ] bug report => search github for a similar issue or PR before submitting
[  ] feature request
```

* **Ngx-pipes version:** 2.0.3

**Current behavior**
error TS2305: Module './node_modules/ngx-pipes/ngx-pipes"' has no exported member 'RangePipe'.

**Minimal reproduction of the problem with instructions**
```typescript
import { RangePipe } from 'ngx-pipes';
```

* **Angular version:** 5.0.1

**Comment by danrevah** [comment]
You should have exported it as part of your pull-request.
Anyway it's fixed now, update to `v2.0.4`.
