### ISSUE TITLE
ngx pipe module building along with .ts file

### ISSUE THREAD

**Issue by sekharz518** [danrevah/ngx-pipes#95]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

* **Ngx-pipes version:** 1.X.X

```
1.6.6
```

**Current behavior**

```
ngx-pipes is failing as the build include .ts files. 
```

**Expected behavior**

```
angular cli try to compile .ts files from ngx pipe modules
```

**Minimal reproduction of the problem with instructions**

```
ERROR in ./node_modules/ngx-pipes/src/app/pipes/helpers/helpers.ts
Module build failed: Error: D:\project\node_modules\ngx-pipes\src\app\pipes\helpers\helpers.ts is not part of the compilation.

```

**Please tell us about your environment:**

```
Windows 7, Visual Studio 1.6.1 
```

* **Angular version:** 5.0.X

```
5.0.1
```

* **Node (for AoT issues):** `node --version` =   
```
8.7.0
```

**Comment by danrevah** [comment]
Try updating to version `2.0.0`

**Comment by sekharz518** [comment]
npm WARN ngx-pipes@2.0.5 requires a peer of @angular/core@^4.0.1 || ~5.0.0 but none is installed. 
I see these warning in my npm install. 

Even I change my package to  ngx-pipes@2.0.0. I still see same warning in my console.

**Comment by sekharz518** [comment]
I updated to Angular 5 with all my @angular packages to 5.1.0
