### ISSUE TITLE
ngx-pipes shows error after updating to angular 5.

### ISSUE THREAD

**Issue by tamilvanan101** [danrevah/ngx-pipes#98]
Hi,
 After updating angular and ngx-pipes version to latest, I am getting this error while running npm start.

ERROR in ./src/app/shared/shared.module.ts
Module not found: Error: Can't resolve 'ngx-pipes/src/pipes/array/order-by-impure' in 'D:\tamilbackup\25072017\angularworkfolder\src\app\shared'
resolve 'ngx-pipes/src/pipes/array/order-by-impure' in 'D:\tamilbackup\25072017\angularworkfolder\src\app\shared'
  Parsed request is a module
  using description file: D:\tamilbackup\25072017\angularworkfolder\package.json (relative path: ./src/app/shared)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\tamilbackup\25072017\angularworkfolder\package.json (relative path: ./src/app/shared)
    resolve as module
      D:\tamilbackup\25072017\angularworkfolder\src\app\shared\node_modules doesn't exist or is not a directory
      D:\tamilbackup\25072017\angularworkfolder\src\app\node_modules doesn't exist or is not a directory
      D:\tamilbackup\25072017\angularworkfolder\src\node_modules doesn't exist or is not a directory
      D:\tamilbackup\25072017\node_modules doesn't exist or is not a directory
      D:\tamilbackup\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      looking for modules in D:\tamilbackup\25072017\angularworkfolder\node_modules
        using description file: D:\tamilbackup\25072017\angularworkfolder\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\tamilbackup\25072017\angularworkfolder\package.json (relative path: ./node_modules)
          using description file: D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\package.json (relative path: ./src/pipes/array/order-by-impure)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure.js doesn't exist
            as directory
              D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure doesn't exist
      looking for modules in D:\tamilbackup\25072017\angularworkfolder\node_modules
        using description file: D:\tamilbackup\25072017\angularworkfolder\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\tamilbackup\25072017\angularworkfolder\package.json (relative path: ./node_modules)
          using description file: D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\package.json (relative path: ./src/pipes/array/order-by-impure)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure.js doesn't exist
            as directory
              D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure doesn't exist
      looking for modules in D:\tamilbackup\25072017\angularworkfolder\src\src
        using description file: D:\tamilbackup\25072017\angularworkfolder\package.json (relative path: ./src/src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\tamilbackup\25072017\angularworkfolder\package.json (relative path: ./src/src)
          using description file: D:\tamilbackup\25072017\angularworkfolder\package.json (relative path: ./src/src/ngx-pipes/src/pipes/array/order-by-impure)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure.js doesn't exist
            as directory
              D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure doesn't exist
      looking for modules in D:\tamilbackup\25072017\angularworkfolder\src\src
        using description file: D:\tamilbackup\25072017\angularworkfolder\package.json (relative path: ./src/src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\tamilbackup\25072017\angularworkfolder\package.json (relative path: ./src/src)
          using description file: D:\tamilbackup\25072017\angularworkfolder\package.json (relative path: ./src/src/ngx-pipes/src/pipes/array/order-by-impure)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure.js doesn't exist
            as directory
              D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure doesn't exist
[D:\tamilbackup\25072017\angularworkfolder\src\app\shared\node_modules]
[D:\tamilbackup\25072017\angularworkfolder\src\app\node_modules]
[D:\tamilbackup\25072017\angularworkfolder\src\node_modules]
[D:\tamilbackup\25072017\node_modules]
[D:\tamilbackup\node_modules]
[D:\node_modules]
[D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure]
[D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure.ts]
[D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure.js]
[D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure]
[D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure]
[D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure.ts]
[D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure.js]
[D:\tamilbackup\25072017\angularworkfolder\node_modules\ngx-pipes\src\pipes\array\order-by-impure]
[D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure]
[D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure.ts]
[D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure.js]
[D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure]
[D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure]
[D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure.ts]
[D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure.js]
[D:\tamilbackup\25072017\angularworkfolder\src\src\ngx-pipes\src\pipes\array\order-by-impure]
 @ ./src/app/shared/shared.module.ts 10:0-78
 @ ./src/app/systemsetup/systemsetup.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
-----------------------------------
My shared.module.ts details

import { NgModule } from '@angular/core';
import { NgArrayPipesModule } from 'ngx-pipes';
import { OrderByImpurePipe } from 'ngx-pipes/src/pipes/array/order-by-impure';

@NgModule({
  imports: [   NgArrayPipesModule,   ]
....
providers: [ OrderByImpurePipe ] 

----------------------------------
My package.json details

 "dependencies": {
    "@ angular/animations": "^5.1.0",
    "@ angular/cdk": "^5.0.1",
    "@ angular/common": "^5.1.0",
    "@ angular/compiler": "^5.1.0",
    "@ angular/core": "^5.1.0",
    "@ angular/forms": "^5.1.0",
    "@ angular/material": "^5.0.1",
    "@ angular/platform-browser": "^5.1.0",
    "@ angular/platform-browser-dynamic": "^5.1.0",
    "@ angular/router": "^5.1.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.1",
    "hammerjs": "^2.0.8",
    "html5-history-api": "^4.2.8",
    "intl": "^1.2.5",
    "ngx-pagination": "^3.0.3",
    "ngx-pipes": "^2.0.5",
    "rxjs": "^5.5.5",
    "ts-helpers": "^1.1.2",
    "zone.js": "^0.8.18"
  },

**Comment by danrevah** [comment]
It's related to the fact you updated to `ngx-pipes` - v2.0.5
In version 2 there has been a breaking change.
https://github.com/danrevah/ngx-pipes/blob/master/CHANGELOG.md

You should now import the OrderByImpurePipe by using `import { OrderByImpurePipe } from 'ngx-pipes';`

**Comment by tamilvanan101** [comment]
Thanks. It is working now.
