### ISSUE TITLE
Array.reverse modifies existing array.

### ISSUE THREAD

**Issue by mbonig** [danrevah/ngx-pipes#99]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
```

* **Ngx-pipes version:** 2.0.5

**Current behavior**
Right now I'm using the 'reverse' pipe like so:
`let note in notes$ | async | reverse` where notes$ is an observable to a central app state (ng2-redux and @select is used to get this observable). The `reverse` pipe uses an in-place Array.reverse call, modifying the existing array and also the appstate, which is a big no-no in the redux world.

**Expected behavior**
I would have expected the pipe to instead return a new array instead of modifying the existing array, either by default or by passing an optional parameter to request a new array be created.

**Minimal reproduction of the problem with instructions**
Please let me know if you need an example. I think the issue is pretty clearly defined. 

**Please tell us about your environment:**

* **Angular version:** 5.0.0

* **Node (for AoT issues):** `node --version` =   v8.7.0

**Comment by danrevah** [comment]
I'd do my best to find a time to solve this, but a pull request would be great :)
